services:
  main-scraper:
    platform: linux/arm64
    image: ${DOCKER_IMAGE_NAME:-ghcr.io/liante0904/stock-noti-bot:latest}
    container_name: telegram-stock-info-noti-bot-main-scraper-${APP_ENV:-dev}
    
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    network_mode: "host"
    env_file:
      - .env
    volumes:
      - ~/log:/log
      - ~/sqlite3:/app/db
    environment:
      - APP_ENV=${APP_ENV:-dev}
      - TZ=Asia/Seoul
      - LOG_BASE_DIR=/log
      - LOG_FILE=/log/logfile.log
      - SQLITE_DB_PATH=/app/db/telegram.db
      - SOCKS_PROXY_URL=socks5h://localhost:9091
    stdin_open: true
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  report-keyword-alert:
    platform: linux/arm64
    image: ${DOCKER_IMAGE_NAME:-ghcr.io/liante0904/stock-noti-bot:latest}
    container_name: telegram-stock-info-noti-bot-keyword-alert-${APP_ENV:-dev}
    
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    network_mode: "host"
    env_file: .env
    volumes:
      - ~/sqlite3:/app/db
      - ~/log:/log
    environment:
      - APP_ENV=${APP_ENV:-dev}
      - SQLITE_DB_PATH=/app/db/telegram.db
      - LOG_BASE_DIR=/log
      - TZ=Asia/Seoul
      - POSTGRES_HOST=localhost
    command: ["uv", "run", "scheduler_keyword_alert.py"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
