import asyncio
import oracledb
import os
import sys
from datetime import datetime, timedelta
from dotenv import load_dotenv

# 현재 스크립트의 상위 디렉터리를 모듈 경로에 추가
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from models.FirmInfo import FirmInfo

# 환경 변수 로드
load_dotenv()

# Oracle 설정
WALLET_LOCATION = os.getenv('WALLET_LOCATION')
WALLET_PASSWORD = os.getenv('WALLET_PASSWORD')
DB_USER = os.getenv('DB_USER')
DB_PASSWORD = os.getenv('DB_PASSWORD')
DB_DSN = os.getenv('DB_DSN')

class OracleManager:
    def __init__(self):
        """Oracle 데이터베이스 연결 초기화 (Thick 모드 및 Wallet 처리)"""
        self.conn = None
        # Oracle Thick 모드 초기화 (필요한 경우)
        # try:
        #     oracledb.init_oracle_client(lib_dir="/path/to/instantclient")
        # except Exception as e:
        #     pass

    async def _get_connection(self):
        """비동기 연결 객체 반환"""
        return await oracledb.connect_async(
            user=DB_USER,
            password=DB_PASSWORD,
            dsn=DB_DSN,
            config_dir=WALLET_LOCATION,
            wallet_location=WALLET_LOCATION,
            wallet_password=WALLET_PASSWORD
        )

    async def create_table(self):
        """프로그램 목적에 맞는 새로운 테이블 생성 (TB_SEC_REPORTS)"""
        query = """
        CREATE TABLE TB_SEC_REPORTS (
            REPORT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            SEC_FIRM_ORDER NUMBER,
            ARTICLE_BOARD_ORDER NUMBER,
            FIRM_NM VARCHAR2(200),
            REG_DT VARCHAR2(20),
            ATTACH_URL VARCHAR2(1000),
            ARTICLE_TITLE VARCHAR2(1000),
            ARTICLE_URL VARCHAR2(1000),
            SEND_USER VARCHAR2(4000),
            MAIN_CH_SEND_YN CHAR(1) DEFAULT 'N',
            DOWNLOAD_STATUS_YN CHAR(1) DEFAULT 'N',
            DOWNLOAD_URL VARCHAR2(1000),
            SAVE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            WRITER VARCHAR2(200),
            REPORT_KEY VARCHAR2(500) UNIQUE,
            TELEGRAM_URL VARCHAR2(1000),
            MKT_TP VARCHAR2(20) DEFAULT 'KR',
            GEMINI_SUMMARY CLOB,
            SUMMARY_TIME VARCHAR2(50),
            SUMMARY_MODEL VARCHAR2(100)
        )
        """
        try:
            conn = await self._get_connection()
            async with conn.cursor() as cursor:
                await cursor.execute(query)
                await conn.commit()
            await conn.close()
            print("Table 'TB_SEC_REPORTS' created successfully.")
        except oracledb.DatabaseError as e:
            error_obj, = e.args
            if error_obj.code == 955: # ORA-00955: name is already used by an existing object
                print("Table 'TB_SEC_REPORTS' already exists.")
            else:
                print(f"Error creating table: {e}")

    async def insert_json_data_list(self, json_data_list):
        """JSON 데이터 리스트를 Oracle DB에 MERGE(UPSERT) 방식으로 삽입"""
        conn = await self._get_connection()
        
        # Oracle MERGE INTO 문 (UPSERT 처리)
        # KEY는 Oracle 예약어이므로 REPORT_KEY를 사용합니다.
        query = """
        MERGE INTO TB_SEC_REPORTS t
        USING (SELECT :SEC_FIRM_ORDER as SEC_FIRM_ORDER, :ARTICLE_BOARD_ORDER as ARTICLE_BOARD_ORDER, 
                      :FIRM_NM as FIRM_NM, :REG_DT as REG_DT, :ATTACH_URL as ATTACH_URL, 
                      :ARTICLE_TITLE as ARTICLE_TITLE, :ARTICLE_URL as ARTICLE_URL, 
                      :MAIN_CH_SEND_YN as MAIN_CH_SEND_YN, :DOWNLOAD_URL as DOWNLOAD_URL, 
                      :TELEGRAM_URL as TELEGRAM_URL, :WRITER as WRITER, :MKT_TP as MKT_TP, 
                      :REPORT_KEY as REPORT_KEY, TO_TIMESTAMP(:SAVE_TIME, 'YYYY-MM-DD"T"HH24:MI:SS.FF') as SAVE_TIME
               FROM DUAL) s
        ON (t.REPORT_KEY = s.REPORT_KEY)
        WHEN MATCHED THEN
            UPDATE SET 
                t.REG_DT = s.REG_DT,
                t.WRITER = s.WRITER,
                t.MKT_TP = s.MKT_TP,
                t.DOWNLOAD_URL = CASE WHEN s.DOWNLOAD_URL IS NOT NULL THEN s.DOWNLOAD_URL ELSE t.DOWNLOAD_URL END,
                t.TELEGRAM_URL = CASE WHEN s.TELEGRAM_URL IS NOT NULL AND s.TELEGRAM_URL != '' THEN s.TELEGRAM_URL ELSE t.TELEGRAM_URL END
        WHEN NOT MATCHED THEN
            INSERT (SEC_FIRM_ORDER, ARTICLE_BOARD_ORDER, FIRM_NM, REG_DT, ATTACH_URL, 
                    ARTICLE_TITLE, ARTICLE_URL, MAIN_CH_SEND_YN, DOWNLOAD_URL, 
                    TELEGRAM_URL, WRITER, MKT_TP, REPORT_KEY, SAVE_TIME)
            VALUES (s.SEC_FIRM_ORDER, s.ARTICLE_BOARD_ORDER, s.FIRM_NM, s.REG_DT, s.ATTACH_URL, 
                    s.ARTICLE_TITLE, s.ARTICLE_URL, s.MAIN_CH_SEND_YN, s.DOWNLOAD_URL, 
                    s.TELEGRAM_URL, s.WRITER, s.MKT_TP, s.REPORT_KEY, s.SAVE_TIME)
        """
        
        params_list = []
        for entry in json_data_list:
            # MKT_TP 자동 판별 로직 (트리거 대신 Python에서 처리)
            title = entry.get("ARTICLE_TITLE", "")
            mkt_tp = entry.get("MKT_TP", "KR")
            if not mkt_tp or mkt_tp == "KR":
                if ".JP" in title: mkt_tp = "JP"
                elif ".US" in title: mkt_tp = "US"
            
            # SAVE_TIME 포맷팅 (ISO 형식 2024-03-05T12:00:00 -> Oracle TIMESTAMP)
            st = entry["SAVE_TIME"]
            if "T" not in st: # 만약 '2024-03-05 12:00:00' 형식이면 T로 변환
                st = st.replace(" ", "T")

            params_list.append({
                "SEC_FIRM_ORDER": entry["SEC_FIRM_ORDER"],
                "ARTICLE_BOARD_ORDER": entry["ARTICLE_BOARD_ORDER"],
                "FIRM_NM": entry["FIRM_NM"],
                "REG_DT": entry.get("REG_DT", ""),
                "ATTACH_URL": entry.get("ATTACH_URL", ""),
                "ARTICLE_TITLE": title,
                "ARTICLE_URL": entry.get("ARTICLE_URL"),
                "MAIN_CH_SEND_YN": entry.get("MAIN_CH_SEND_YN", "N"),
                "DOWNLOAD_URL": entry.get("DOWNLOAD_URL"),
                "TELEGRAM_URL": entry.get("TELEGRAM_URL", ""),
                "WRITER": entry.get("WRITER", ""),
                "MKT_TP": mkt_tp,
                "REPORT_KEY": entry.get("KEY") or entry.get("ATTACH_URL", ""),
                "SAVE_TIME": st
            })
            
        try:
            async with conn.cursor() as cursor:
                await cursor.executemany(query, params_list)
                await conn.commit()
            print(f"Merge completed: {len(params_list)} rows processed.")
        except oracledb.DatabaseError as e:
            print(f"Error during merge: {e}")
        finally:
            await conn.close()
        return len(params_list)

    async def execute_query(self, query, params=None):
        """공통 비동기 쿼리 실행기"""
        conn = await self._get_connection()
        try:
            async with conn.cursor() as cursor:
                if params:
                    await cursor.execute(query, params)
                else:
                    await cursor.execute(query)
                
                if query.strip().lower().startswith("select"):
                    rows = await cursor.fetchall()
                    columns = [desc[0] for desc in cursor.description]
                    result = [dict(zip(columns, row)) for row in rows]
                else:
                    await conn.commit()
                    result = {"status": "success", "affected_rows": cursor.rowcount}
                return result
        except Exception as e:
            return {"status": "error", "error": str(e)}
        finally:
            await conn.close()

    async def daily_select_data(self, date_str=None, type=None):
        """지정된 날짜의 전송/다운로드 대상 조회 (Oracle용 날짜 함수 적용)"""
        if type not in ['send', 'download']:
            raise ValueError("Invalid type. Must be 'send' or 'download'.")

        if date_str is None:
            query_date = datetime.now().strftime('%Y-%m-%d')
            query_reg_dt = (datetime.now() + timedelta(days=2)).strftime('%Y%m%d')
        else:
            query_date = f"{date_str[:4]}-{date_str[4:6]}-{date_str[6:]}"
            query_reg_dt = (datetime.strptime(date_str, '%Y%m%d') + timedelta(days=2)).strftime('%Y%m%d')

        three_days_ago = (datetime.now() - timedelta(days=3)).strftime('%Y%m%d')

        if type == 'send':
            query_condition = "(MAIN_CH_SEND_YN != 'Y' OR MAIN_CH_SEND_YN IS NULL) AND (SEC_FIRM_ORDER != 19 OR (SEC_FIRM_ORDER = 19 AND TELEGRAM_URL IS NOT NULL))"
        elif type == 'download':
            query_condition = "MAIN_CH_SEND_YN = 'Y' AND DOWNLOAD_STATUS_YN != 'Y'"

        # Oracle에 맞춰 TO_CHAR 및 날짜 연산 수정
        query = f"""
        SELECT 
            REPORT_ID as id, SEC_FIRM_ORDER, ARTICLE_BOARD_ORDER, FIRM_NM, REG_DT,
            ATTACH_URL, ARTICLE_TITLE, ARTICLE_URL, MAIN_CH_SEND_YN, 
            DOWNLOAD_URL, WRITER, SAVE_TIME, TELEGRAM_URL
        FROM 
            TB_SEC_REPORTS 
        WHERE 
            TO_CHAR(SAVE_TIME, 'YYYY-MM-DD') = :query_date
            AND REG_DT >= :three_days_ago
            AND REG_DT <= :query_reg_dt
            AND {query_condition}
        ORDER BY SEC_FIRM_ORDER, ARTICLE_BOARD_ORDER, SAVE_TIME
        """
        
        params = {
            "query_date": query_date,
            "three_days_ago": three_days_ago,
            "query_reg_dt": query_reg_dt
        }
        
        return await self.execute_query(query, params)

    async def daily_update_data(self, fetched_rows=None, type=None):
        """상태 업데이트 (전송완료/다운로드완료)"""
        if type not in ['send', 'download']:
            raise ValueError("Invalid type. Must be 'send' or 'download'.")

        conn = await self._get_connection()
        try:
            async with conn.cursor() as cursor:
                if type == 'send':
                    query = "UPDATE TB_SEC_REPORTS SET MAIN_CH_SEND_YN = 'Y' WHERE REPORT_ID = :id"
                    # fetched_rows가 리스트인 경우와 단일 객체인 경우 처리
                    if isinstance(fetched_rows, list):
                        params = [{"id": row['id'] if 'id' in row else row['ID']} for row in fetched_rows]
                        await cursor.executemany(query, params)
                    else:
                        await cursor.execute(query, {"id": fetched_rows['id'] if 'id' in fetched_rows else fetched_rows['ID']})
                
                elif type == 'download':
                    query = "UPDATE TB_SEC_REPORTS SET DOWNLOAD_STATUS_YN = 'Y' WHERE REPORT_ID = :id"
                    await cursor.execute(query, {"id": fetched_rows['id'] if 'id' in fetched_rows else fetched_rows['ID']})
                
                await conn.commit()
                return {"status": "success", "affected_rows": cursor.rowcount}
        finally:
            await conn.close()

    async def update_telegram_url(self, record_id, telegram_url, article_title=None):
        """텔레그램 URL 업데이트"""
        if article_title:
            query = "UPDATE TB_SEC_REPORTS SET TELEGRAM_URL = :url, ARTICLE_TITLE = :title WHERE REPORT_ID = :id"
            params = {"url": telegram_url, "title": article_title, "id": record_id}
        else:
            query = "UPDATE TB_SEC_REPORTS SET TELEGRAM_URL = :url WHERE REPORT_ID = :id"
            params = {"url": telegram_url, "id": record_id}
        
        return await self.execute_query(query, params)

    async def update_report_summary(self, record_id, summary, model_name):
        """Gemini 요약 결과 업데이트"""
        query = """
        UPDATE TB_SEC_REPORTS
        SET GEMINI_SUMMARY = :summary, 
            SUMMARY_TIME = :st, 
            SUMMARY_MODEL = :model
        WHERE REPORT_ID = :id
        """
        params = {
            "summary": summary,
            "st": datetime.now().isoformat(),
            "model": model_name,
            "id": record_id
        }
        return await self.execute_query(query, params)

async def test_migration():
    # 간단한 테스트 및 테이블 생성
    om = OracleManager()
    await om.create_table()
    print("Migration Test Done.")

if __name__ == "__main__":
    asyncio.run(test_migration())
